# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9844bb5c15c53cb678ac8bc42445e27ba02ba2e75ebacfc782dac4bcc89e078c4b400f8050f47b359d5fdd01250a5062ff3b6b661968b674fcecc6ba5d64a862

test:
  secret_key_base: 2d63692d141dbe52c28ae34d62cb78a012535136423b08bccddbcf1922251f3b512aaa3562b4f1e61e4d29b8fef447c16e161a40b79f7df74529a73a4813e0a7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
